<?php
return [
    'adminEmail' => 'kandepohetest@gmail.com',
    'supportEmail' => 'support@example.com',
    'user.passwordResetTokenExpire' => 3600,
    'pageError' => 'Sorry but there was an error: ',
    'sendInterestMessage' => '#NAME#  interested in your profile.',
    'phoneNumberSeeMessage' => '#NAME# viewed your phone number.',
    'modalTitle' => 'Confirmation',
    'acceptRequest' => 'Are You sure want to Accept Request ?',
    'declineRequest' => 'Are You sure want to Reject Request ?',
    'requestAccepted' => '#NAME# is accepted your request.',
    'searchingLimit' => 3,
    'noRecordsFoundInSearchList' => 'There are no record found as per your searching criteria.',
    'loginFirst' => 'For this you have to login first...!',
    'accessDenied' => 'Access Denied',
    'accessDeniedYourProfile' => "You can't see your profile as user view.",
    'accessDeniedInvalid' => "Trying to access invalid data.",
    'sendInterest' => " Do You want to Send Interest Request ?",
    'acceptInterest' => " Do You want to Accept Interest ?",
    'declineInterest' => " Do You want to Decline Interest ?",
    'cancelInterest' => " Do You want to Cancel Interest ?",
    'acceptInterestMessage' => '#NAME#  has accepted interest request.',
    'declineInterestMessage' => '#NAME#  has Decline interest request.',
    'cancelInterestMessage' => '#NAME#  has Cancel their interest request.',
    'moreConversationErrorMessage' => 'Conversation no longer available,',
    'sendInterestMessageInbox' => 'Would you like to communicate further ?',
    'mailBoxSendInterestSender' => 'You sent #GENDER# interest request.',
    'mailBoxSendInterestReceiver' => '#GENDER# sent you interest request.',
    'smsGetwayError' => 'Something wrong with SMS sending Process. Please contact to site admin.',
    'photoMissingError' => 'Photo has issue. Please try again !',
    'photoCopyError' => 'Photo saving has issue. Please try again !',
    'photoCropAreaSelection' => 'Please first select photo portion !',


    'total_files_allowed' => 10,
    'max_file_size' => 2048576,
    'maxWidth' => 500,
    'thumbnailPrefix' => 'thumb_',
    'profilePrefix' => '_profile',
    'allowed_file_types' => "'image/png', 'image/gif', 'image/jpeg', 'image/pjpeg'",
    'browserFileSupportError' => 'Your browser does not support new File API! Please upgrade.',
    'fileUploadSize' => 'You are trying to upload photos more than limit.',
    'fileUnsoupportedType' => 'You are trying to upload unsupported file type.',
    'profilePhotoFolder' => 'profile',

];

