<?php
return [
    'adminEmail' => 'kandepohetest@gmail.com',
    'supportEmail' => 'support@example.com',
    'user.passwordResetTokenExpire' => 3600,
    'pageError' => 'Sorry but there was an error: ',
    'sendInterestMessage' => '#NAME#  is interested in your profile.',
    'phoneNumberSeeMessage' => '#NAME# is  viewed your phone number.',
    'modalTitle' => 'Confirmation',
    'acceptRequest' => 'Are You sure want to Accept Request ?',
    'declineRequest' => 'Are You sure want to Reject Request ?',
    'requestAccepted' => '#NAME#  is accepted your request.',
    'searchingLimit' => 3,
    'noRecordsFoundInSearchList' => 'There are no record found as per your searching criteria.',
    'loginFirst' => 'For this you have to login first...!',
    'accessDenied' => 'Access Denied',
    'accessDeniedYourProfile' => "You can't see your profile as user view.",
    'accessDeniedInvalid' => "Trying to access invalid data.",
    'sendInterest' => " Do You want to Accept Interest ?",
    'acceptInterest' => " Do You want to Accept Interest ?",
    'declineInterest' => " Do You want to Decline Interest ?",
    'acceptInterestMessage' => '#NAME#  has accepted your request.',
    'declineInterestMessage' => '#NAME#  has accepted your request.',
];

